version: '3.8'

services:
  # 1. Spring Boot Web Service
  web:
    # Build the image using the Dockerfile in the current directory
    build: .
    ports:
      - "8080:8080"
    # Ensure the database starts before the web app tries to connect
    depends_on:
      - db
    environment:
      # These environment variables link to your application.properties
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: task_manager
      DB_USER: root
      DB_PASSWORD: 1234 

  # 2. MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      # Required for MySQL image initialization
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: task_manager
    volumes:
      # Creates a persistent volume to save database data
      - db_data:/var/lib/mysql
    
    # === FIX: Keep the MySQL server running in the foreground ===
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: